---
title: ULC Team Resources Site
timezone: UTC
collections:
  acm:
    title: ACM
    output: true
  archives-west:
    title: Archives West
    output: true
  dcbp:
    title: DCBP
    output: true
  groups:
    title: Groups
    output: true
  ir:
    title: IR
    output: true
  oer:
    title: OER
    output: true
  posts:
    title: Posts
    output: true
  umsils:
    title: UMSILS
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: groups
  values:
    layout: group
tagline: a theme for building simple digital exhibits
description: CollectionBuilder-GH is a template for creating small digital collection
  exhibits on GitHub Pages designed for teaching digital library skills
keywords: ULC, Orbis Cascade Alliance, IR, Archives, OER, Digital Collections
author: dcnb
url: https://orbiscascadeULC.github.io
repository: https://github.com/orbiscascadeULC/
fontawesome: true
bootswatch: 
permalink: pretty
